# DO NOT EDIT generated by 'terraflake init' (version: 0.3.0)

{ lib, modulesPath, pkgs, config, ... }: with builtins; let
  node = config.terraflake.input.nodes."hetzvps";
  nodeConf'.modulesPath = modulesPath;
  hashDir = dir:
    mapAttrs (k: v: let p = "${dir}/${k}"; in
      if v == "regular" then hashFile "sha1" p
      else if v == "directory" then hashDir p
      else "")
    (readDir dir);
  hash = path: let p = toString path; in
    if (readDir (dirOf p))."${baseNameOf p}" == "directory"
    then hashString "sha1" (toJSON (hashDir p))
    else hashFile "sha1" p;
in {
  imports = [
    # Input data
    ./.input.nix
    # Secrets module
    ({ lib, config, ... }: with lib; {
      options.terraflake.system = mkOption {
        description = "Remote system.";
        type = types.str;
      };
      options.terraflake.input = mkOption {
        description = "Data passed from provisioner.";
        type = with types; submodule { options = {
          meta = mkOption { type = attrs; };
          nodes = mkOption { type = attrs; };
          node = mkOption { type = attrs; };
        }; };
        default = { meta = {}; nodes = {}; node = {}; };
      };
      options.terraflake.filesIn = mkOption {
        description = "Attrset of paths to local files, name -> local path.";
        type = with types; attrsOf (submodule { options = {
          path = mkOption { type = path; };
          links = mkOption { type = listOf str; default = []; };
          chmod = mkOption { type = strMatching "[0-7]+"; default = "0600"; };
          user = mkOption { type = enum (attrNames config.users.users); default = "root"; };
          group = mkOption { type = enum (attrNames config.users.groups); default = "root"; };
        };});
        default = {};
      };
      options.terraflake.filesDir = mkOption {
        description = "Remote directory path to upload files to.";
        type = types.str;
        default = "/var/lib/nf-keys";
      };
      options.terraflake.filesOut = mkOption {
        description = "Attrset of paths to remote files, name -> server path.";
        type = with types; attrsOf str;
        default = {};
      };
      config.terraflake.input.node = node;
      config.terraflake.filesOut = mapAttrs (k: v: config.terraflake.filesDir+"/"+(hash v.path)) config.terraflake.filesIn;
      config.system.activationScripts.nf-keys-permissons = concatMapStrings
        (k: let
          i = config.terraflake.filesIn."${k}";
          o = config.terraflake.filesOut."${k}";
        in ''
          chown -R "${i.user}:${i.group}" "${o}"
          ${concatMapStringsSep "\n" (ln: "ln -sfT '${o}' '${ln}'") i.links}
        '')
        (attrNames config.terraflake.filesIn);
    })

    # Hardware config gernerated by nixos-infect: hcloud
    ({ lib, ... }: {
  # This file was populated at runtime with the networking
  # details gathered from the active system.
  networking = {
    nameservers = [ "8.8.8.8"
 ];
    defaultGateway = "172.31.1.1";
    defaultGateway6 = {
      address = "fe80::1";
      interface = "eth0";
    };
    dhcpcd.enable = false;
    usePredictableInterfaceNames = lib.mkForce false;
    interfaces = {
      eth0 = {
        ipv4.addresses = [
          { address="37.27.186.30"; prefixLength=32; }
        ];
        ipv6.addresses = [
          { address="2a01:4f9:c012:abe4::1"; prefixLength=64; }
{ address="fe80::9400:4ff:fe18:7016"; prefixLength=64; }
        ];
        ipv4.routes = [ { address = "172.31.1.1"; prefixLength = 32; } ];
        ipv6.routes = [ { address = "fe80::1"; prefixLength = 128; } ];
      };
      
    };
  };
  services.udev.extraRules = ''
    ATTR{address}=="96:00:04:18:70:16", NAME="eth0"
    
  '';
})
    ({ modulesPath, ... }:
{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];
  boot.loader.grub.device = "/dev/sda";
  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "xen_blkfront" "vmw_pvscsi" ];
  boot.initrd.kernelModules = [ "nvme" ];
  fileSystems."/" = { device = "/dev/sda1"; fsType = "ext4"; };
  
})
    ({ ... }: { terraflake.system = "x86_64-linux"; })

    # Node specific config
    # nodeConf'.configuration
  ];
  networking.hostName = "hetzvps";
  services.openssh.enable = true;
  users.users.root.openssh.authorizedKeys.keys = [node.ssh_key];
  #system.activationScripts.nixos-cleanup = "rm -rf /old-root /boot.bak || true";
}
